version: "3"
services:

  vscode:
    image: braintwister/ubuntu-18.04-vscode-1.40
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro 
      - /etc/localtime:/etc/localtime:ro
      - home:/home/${USER_NAME}
      - ${GIT_DIR}:/home/${USER_NAME}/git
    environment:
      - DISPLAY
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - USER_NAME=${USER_NAME}
      - GROUP_NAME=${GROUP_NAME}
    privileged: true

volumes:
  home:
